services:
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=examByte"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=iamgroot"